### ISSUE TITLE
base it on git commit

### ISSUE THREAD

**Issue by stephanschulz** [jjssoftware/autoVersioning#1]
Hey. Thanks for this create addition.

I was wondering if you see a way to query the local git commit info to generate a version number.

In c++ with openframeworks I have done something like:
```
 string xcodeMsg = ofSystem("xcode-select -p");
    ofLog()<<"xcodeMsg "<<xcodeMsg<<"@";
    string commit;
    string commitVersion;
    string versionDate;
    string versionCount;
    
    if( xcodeMsg == "" ){
        commit = "";
    }else{
        commit = ofSystem("git rev-parse --short HEAD");
        ofStringReplace(commit,"\n","");
        cout<<"git rev-parse HEAD "<<commit<<endl;
        
        versionCount = ofSystem("git rev-list HEAD --count");
        ofStringReplace(versionCount,"\n","");
        cout<<"git rev-list HEAD --count "<<versionCount<<endl;
        
        versionDate = ofSystem("git log -1 --date=short --pretty=format:%cd");
        //    string versionDate = ofSystem("git log -1 --date=short --pretty=format:%Y%m%d");
        //    string versionDate = ofSystem("git rev-list --format=format:'%ai' --max-count=1 `git rev-parse HEAD`");
        ofStringReplace(versionDate,"\n","");
        ofStringReplace(versionDate,"-","");
        ofLog()<<"versionDate "<<versionDate; //.substr(2);
    }
```

thanks outputs this

versionString 40 20180405 f8f895f
versionString numOfCommit date commitSnippet.

thanks for any advice.
stephan

**Comment by bebo-dot-dev** [comment]
Hi Stephan, you're welcome I hope this is useful in some way. 

You didn't say what the constraints are for what you're trying to achieve when using a git commit as a version number so it's a bit difficult to suggest anything semi-useful that won't be way off the mark at the moment. 

Are you asking if it's possible to use build-time gcc preprocessor macros in a similar way as is demoed in this repo combined with git? Or do you have something different in mind?

**Comment by stephanschulz** [comment]
I see that your code mainly uses macros and I was wondering if there is a way for a C header (like build_defs.h) to also pull in other system information. Like info about the latest git commit of this code as I am doing in my c++ code.
I have a feeling that's not possible since none of the git info is a macro.

**Comment by bebo-dot-dev** [comment]
Ah cool thanks for clarifying. I'll have a think and see what I can come up with.

**Comment by bebo-dot-dev** [comment]
Hi Stephan, I took a look and this is what I found: 

The gcc preprocessor is not going to be able to do this on it's own because what you're basically needing is a way to call git via a shell command to populate one or more `#define` directives and the preprocessor doesn't natively support anything like this. The code in `build_defs.h` in this project works because `__DATE__` and `__TIME__` are valid gcc preprocessor [standard predefined macros](https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html)

The good news is that I'm sure what you want to do is possible but the way you go about it will depend on how you use gcc and the toolchain you develop with. This SO post should give you some ideas because it's pretty much exactly what you want to do (other than it not directly demonstrating a call to git): 

https://stackoverflow.com/questions/5319289/can-the-gcc-c-preprocessor-use-the-output-of-a-shell-command

I'm a PlatformIO guy at the moment so if I wanted to do something like this in PlatformIO I'd use a pre-build python script to create a .h file i.e. http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html

If you're an Eclipse developer then you'd likely have direct access to modifying a makefile to do this kind of thing.

Other IDEs / toolchains will likely have other options to do this kind of thing..

There's probably a bit more work for you to do here to wire this into your environment but it should point you in the right direction. I hope that helps in some way :)

**Comment by stephanschulz** [comment]
Thank you very much Joe taking the time looking in to this.
I love your way of using the macros because it means no medications need to be done to the file relating to the Arduino IDE or the platform.txt
I'm worried that every time I use a different board type or update the IDE I have to remember to redo those modifications. Not so with your approach.
I do like the idea of somehow generating a custom .h file. Maybe when ever I submit to git my git application can generate new content for the header file. 
I will take a look in to that.
thanks again.

**Comment by stephanschulz** [comment]
I guess .git/hooks is where I would put my script that generates the version.h for the Arduino sketch.
Fun learning about new things. :)

**Comment by bebo-dot-dev** [comment]
This sounds like a demo project in the making for a new GitHub repo to me 😉

I say go for it and publish your results when you're done. It might be useful for other people to use or learn from.

**Comment by stephanschulz** [comment]
I think I was able to make a working version. Thanks for your advice.
https://github.com/antimodular/version-numbers

**Comment by bebo-dot-dev** [comment]
No worries, https://github.com/antimodular/version-numbers/blob/master/versionNum_arduino/create_git_versionNum.sh looks like a winner to me, well done.

I think you were right when you mentioned using a git hook script to automate it and a post-commit hook would probably be the right one for this.

**Comment by stephanschulz** [comment]
Yes, post-commit hooks would be great.
So far I am not sure if sourceTree can do hooks. The forums seem to suggest sourceTree does not really execute the scripts in the hooks folder.
I did create .git/hooks/post-commit and paste a version of my script in there. If I run it via terminal it works but nothing happens when I make a commit via sourceTree.

**Comment by bebo-dot-dev** [comment]
It sounds strange that a git hook not working could be a SourceTree problem because SourceTree is just a git client and git hooks are called by git itself..but I guess it is possible that it is related.

I know that once upon a time SourceTree supported "embedded git" as well as git proper. I'm not sure if that's still the case nowadays but I'd probably lean towards using full git rather that an embedded cut down version myself.

Using SourceTree implies you're a windows or a mac user. What O/S are you running this on?

**Comment by stephanschulz** [comment]
macOS

**Comment by bebo-dot-dev** [comment]
hmm ok, it smells like this: http://axiac.ro/blog/atlassian-sourcetree-and-git-hooks/ .. i.e. possibly path related

**Comment by stephanschulz** [comment]
I saw that post too, but wasn't sure how to apply it to my situation.
so I tried a absolute path and it worked. 
```
cd /Users/berlin/Documents/Arduino/antimodular/Bach_sphere
```

not I just need to work out how to get the current path.
I thought
```
BASEDIR=$(dirname "$0")
echo "$BASEDIR"
cd ../../
```

would give me the path to the post-commit script. and it does if I run it via the terminal.

even when I put this in the post-commit.sh nothing get's created. which makes me think it's not actually running
```
BASEDIR=$(dirname "$0")
echo "$BASEDIR"
> test321.h
cat <<EOT >> test321.h
BASEDIR
$BASEDIR
EOT
```

**Comment by bebo-dot-dev** [comment]
git hook scripts have no file extension, the script needs to be called `post-commit`

https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

> To enable a hook script, put a file in the hooks subdirectory of your .git directory that is named appropriately (without any extension) and is executable. From that point forward, it should be called.

It could just be that this is your problem, but I'm just guessing. It's impossible for me to directly debug what you're seeing here because I'm a linux user.

I can say that the following works for me with git v2.17.0 on Linux Mint v18.3 here:

1. I initialized a new git repo in the /home/joe/Dev/git_repositories/testRepo directory on local (`git init`)
2. I created a new file in this directory (`echo "hello world" >> main.c`)
3. I added the new main.c file to the repo (`git add main.c`) and then committed it (`git commit -a -m "initial commit"`) watching the output at the CLI. This was the output:
```
[master 5c327c4] initial commit
 1 file changed, 1 insertion(+)
```
4. I then added a post-commit script into my /home/joe/Dev/git_repositories/testRepo/.git/hooks directory called `post-commit`, made this script executable and put this content inside that file:
```
#!/bin/sh
LAST_COMMIT=`git log -1 HEAD --pretty=%h`
echo "hello world $LAST_COMMIT from post-commit"
```
5. I modified my "source file" again (`echo "hello world" >> main.c`)
6. I committed this change and was able to see that the post-commit script worked as expected in the CLI output (`git commit -a -m "another commit"`):
```
hello world 52376e4 from post-commit
[master 52376e4] another commit
 1 file changed, 1 insertion(+)
```

I've verified this is working as expected from both the CLI and also when performing commits via SmartGit v17.1 (https://www.syntevo.com/smartgit/)

I _"think"_ there's a way to switch on full console ouput in SourceTree, if so that might be worth a try if you've not already done that; it might give some clues as to what's failing.

**Comment by stephanschulz** [comment]
Joe you are awesome. Your help is very much appreciated. 
I got it all working.
The trick was to not make it have the .sh file extension. 
I don't really know how to generate such file but I just copied one from the .git folder and renamed it. 
After that I called chmod 755 filename
et voila. 
It's done.

Thank you very much for the time you put in to help me.

https://github.com/antimodular/version-numbers/tree/master/versionNum_arduino/git/hooks

**Comment by bebo-dot-dev** [comment]
Hi Stephan you're welcome, I'm happy to hear that you got it working. I just think I got lucky noticing the file was named post-commit.sh in your last comment. 

I think this one is all done now. Feel free to open another issue if you have any more questions.
